name: unit-tests
description: Action to execute unit tests

inputs:
  test-dir:
    description: The directory where the test files are kept
    required: true
    default: tests

outputs:
  coverage: # id of the output
    description: Final test coverage
    value: ${{ steps.coverage-rate.outputs.coverage }}

runs:
  using: "composite"
  steps:
    - name: Install researcher dependencies
      run: | 
        source ~/.bashrc
        conda clean -i -y
        ./scripts/configure_conda researcher
        ./scripts/fedbiomed_run network
      shell: bash -l {0}

    - name: Run unit tests 
      run: |
          PYTHONPATH=${PYTHONPATH:-$PWD} conda run -n fedbiomed-researcher pytest -v --cov=fedbiomed --cov-report term --cov-report xml:${{ inputs.test-dir }}/coverage.xml ${{ inputs.test-dir }}
      shell: bash  -l {0}
      
    - name: Get coverage rate
      id: coverage-rate
      run: |
        COVERAGE=$(python -c \
          "import xml.etree.ElementTree as ET;tree=ET.parse('${{ inputs.test-dir }}/coverage.xml');\
          root=tree.getroot();print(root.attrib['line-rate'])")
        echo $COVERAGE 
        echo "coverage=$(echo $COVERAGE)" >> $GITHUB_OUTPUT
      shell: bash -l {0}
    
    - name: Stop network
      if: always()
      run: | 
        ./scripts/fedbiomed_run network stop
      shell: bash -l {0}
