# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x15PollExperimentRequest\x12\x0c\n\x04node\x18\x01 \x01(\t\"1\n\x16PollExperimentResponse\x12\x17\n\x0f\x65xperiment_name\x18\x01 \x01(\t2}\n\x0e\x46LOrchestrator\x12\x43\n\x0ePollExperiment\x12\x16.PollExperimentRequest\x1a\x17.PollExperimentResponse\"\x00\x12&\n\nOpenStream\x12\x08.Message\x1a\x08.Message\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=17
  _globals['_MESSAGE']._serialized_end=43
  _globals['_POLLEXPERIMENTREQUEST']._serialized_start=45
  _globals['_POLLEXPERIMENTREQUEST']._serialized_end=82
  _globals['_POLLEXPERIMENTRESPONSE']._serialized_start=84
  _globals['_POLLEXPERIMENTRESPONSE']._serialized_end=133
  _globals['_FLORCHESTRATOR']._serialized_start=135
  _globals['_FLORCHESTRATOR']._serialized_end=260
# @@protoc_insertion_point(module_scope)
