site_name: Fed-BioMed Documentation
site_url: https://docs.fedbiomed.org/
site_description: Open-source collaborative learning framework for federated learning and federated analytics.

docs_dir: docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/img/logo_icon.png
  favicon: assets/img/favicon.png
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - navigation.footer

plugins:
  - search:
      lang: en
  - mike
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      custom_templates: docs/.templates
      default_handler: python
      handlers:
        python:
          paths:
            - .
          inventories:
            - https://requests.readthedocs.io/en/master/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://scikit-learn.org/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
          options:
            filters:
              - "!^__"
              - "!^_"
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_source: yes
            show_submodules: false
            show_if_no_docstring: true
            separate_signature: true
            show_category_heading: true
            show_root_toc_entry: no
            show_root_full_path: true
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - stylesheets/extra.css


nav:
  - "Getting Started":
      - "What's Fed-BioMed": "./getting-started/what-is-fedbiomed.md"
      - "Fedbiomed Architecture": "./getting-started/fedbiomed-architecture.md"
      - "Fedbiomed Workflow": "./getting-started/fedbiomed-workflow.md"
      - "Installation": "./getting-started/installation.md"
      - "Basic Example": "./getting-started/basic-example.md"
      - "Configuration": "./getting-started/configuration.md"
  - Tutorials:
      - PyTorch:
          - "MNIST Basic Example": "./tutorials/pytorch/01_PyTorch_MNIST_Single_Node_Tutorial.ipynb"
          - "Create Your Custom Training Plan": "./tutorials/pytorch/02_Create_Your_Custom_Training_Plan.ipynb"
          - "Regression Example with Used Cars Dataset": "./tutorials/pytorch/03_PyTorch_Used_Cars_Dataset_Example.ipynb"
          - "Transfer-Learning in Fed-BioMed": "./tutorials/pytorch/05_Transfer-learning_tutorial_usingDenseNet-121.ipynb"
          - "Aggregators in Fed-BioMed": "./tutorials/pytorch/04-Aggregation_in_Fed-BioMed.ipynb"
      - MONAI:
          - "2D Image Classification with MedNIST": "./tutorials/monai/01_monai-2d-image-classification.ipynb"
          - "2D Image Registration with MedNIST": "./tutorials/monai/02_monai-2d-image-registration.ipynb"
      - Scikit-Learn:
          - "MNIST Basic Example": "./tutorials/scikit-learn/01_sklearn_MNIST_classification_tutorial.ipynb"
          - "Regression with Scikit-Learn": "./tutorials/scikit-learn/02_sklearn_sgd_regressor_tutorial.ipynb"
          - "More Scikit-Learn models": "./tutorials/scikit-learn/03-other-scikit-learn-models.ipynb"
      - Optimizers:
          - "Advanced Optimizers": "./tutorials/optimizers/01-fedopt-and-scaffold.ipynb"
      - Analytics:
          - "Tabular Dataset": "./tutorials/analytics/tabular_dataset.ipynb"
      - FLamby:
          - "Introduction": "./tutorials/flamby/index.md"
          - "FLamby Federated Heart Disease Example": "./tutorials/flamby/flamby-integration-into-fedbiomed.ipynb"
      - Advanced:
          - "In Depth Experiment Configuration": "./tutorials/advanced/in-depth-experiment-configuration.ipynb"
          - "Training with GPU": "./tutorials/advanced/training-with-gpu.ipynb"
          - "Breakpoints": "./tutorials/advanced/breakpoints.md"
      - Security:
          - "Differential Privacy (DP) with OPACUS": "./tutorials/security/differential-privacy-with-opacus-on-fedbiomed.ipynb"
          - "Local and Central DP Example": "./tutorials/security/non-private-local-central-dp-monai-2d-image-registration.ipynb"
          - "Training with Approved Model Files": "./tutorials/security/training-with-approved-training-plans.ipynb"
          - "Secure Aggregation": "./tutorials/security/secure-aggregation.ipynb"
          - "End-to-end Privacy Preserving Training and Inference on Medical Data": "./tutorials/concrete-ml/concrete-ml.ipynb"
      - Biomedical data:
          - "Brain image segmentation using IXI dataset": "./tutorials/medical/medical-image-segmentation-unet-library.ipynb"
          - 'Multi-channel Variational Auto Encoder example using ADNI dataset': './tutorials/medical/mcvae_using_adni_data.ipynb'
  - "User Guide":
      - Glossary: "./user-guide/glossary.md"
      - "Datasets":
          - "Introduction": "./user-guide/datasets/index.md"
          - "Default Datasets": "./user-guide/datasets/default-datasets.md"
          - "Image Datasets": "./user-guide/datasets/image-dataset.md"
          - "Tabular Datasets": "./user-guide/datasets/tabular-dataset.md"
          - "Medical Datasets": "./user-guide/datasets/medical-folder-dataset.md"
          - "Adding your Custom Dataset": "./user-guide/datasets/custom-dataset.md"
          - "Adding a Native Dataset": "./user-guide/datasets/native-dataset.md"
          - "Applying Transformations": "./user-guide/datasets/applying-transformations.md"
          - "Federated Analytics": "./user-guide/datasets/federated-analytics.md"
      - Deployment:
          - "Introduction": "./user-guide/deployment/deployment.md"
          - "VPN Deployment": "./user-guide/deployment/deployment-vpn.md"
          - "Network matrix": "./user-guide/deployment/matrix.md"
          - "Security model": "./user-guide/deployment/security-model.md"
      - Node:
          - "Configuring Nodes": "./user-guide/nodes/configuring-nodes.md"
          - "Deploying Datasets": "./user-guide/nodes/deploying-datasets.md"
          - "Federated Analytics": "./user-guide/nodes/federated-analytics.md"
          - "Training Plan Management": "./user-guide/nodes/training-plan-security-manager.md"
          - "Using GPU": "./user-guide/nodes/using-gpu.md"
          - "Node GUI": "./user-guide/nodes/node-gui.md"
      - Researcher:
          - "Training Plan": "./user-guide/researcher/training-plan.md"
          - "Training Data": "./user-guide/researcher/training-data.md"
          - "Experiment": "./user-guide/researcher/experiment.md"
          - "Aggregation": "./user-guide/researcher/aggregation.md"
          - "Listing Datasets and Selecting Nodes": "./user-guide/researcher/listing-datasets-and-selecting-nodes.md"
          - "Federated Analytics": "./user-guide/researcher/federated-analytics.md"
          - "Model Validation on the Node Side": "./user-guide/researcher/model-testing-during-federated-training.md"
          - "Tensorboard": "./user-guide/researcher/tensorboard.md"
      - Optimization: "./user-guide/advanced-optimization.md"
      - "Secure Aggregation":
          - "Introduction": "./user-guide/secagg/introduction.md"
          - "Configuration": "./user-guide/secagg/configuration.md"
          - "Managing Secure Aggregation in Researcher": "./user-guide/secagg/researcher-interface.md"
  - Developer:
      - "API Reference":
          - Common:
              - Analytics: "./developer/api/common/analytics.md"
              - "Certificate Manager": "./developer/api/common/certificate_manager.md"
              - CLI: "./developer/api/common/cli.md"
              - Config: "./developer/api/common/config.md"
              - Constants: "./developer/api/common/constants.md"
              - DataLoader: "./developer/api/common/dataloader.md"
              - DataLoadingPlan: "./developer/api/common/dataloadingplan.md"
              - DataManager: "./developer/api/common/datamanager.md"
              - "Dataset Controller": "./developer/api/common/dataset_controller.md"
              - "Dataset Reader": "./developer/api/common/dataset_reader.md"
              - Dataset: "./developer/api/common/dataset.md"
              - DB: "./developer/api/common/db.md"
              - Exceptions: "./developer/api/common/exceptions.md"
              - IPython: "./developer/api/common/ipython.md"
              - Json: "./developer/api/common/json.md"
              - Logger: "./developer/api/common/logger.md"
              - Message: "./developer/api/common/message.md"
              - Metrics: "./developer/api/common/metrics.md"
              - Model: "./developer/api/common/models.md"
              - Optimizers: "./developer/api/common/optimizers.md"
              - Privacy: "./developer/api/common/privacy.md"
              - Secagg: "./developer/api/common/secagg.md"
              - "Secagg Manager": "./developer/api/common/secagg_manager.md"
              - Serializer: "./developer/api/common/serializer.md"
              - Singleton: "./developer/api/common/singleton.md"
              - Synchro: "./developer/api/common/synchro.md"
              - TasksQueue: "./developer/api/common/tasks_queue.md"
              - TrainingPlans: "./developer/api/common/training_plans.md"
              - TrainingArgs: "./developer/api/common/training_args.md"
              - Utils: "./developer/api/common/utils.md"
              - Validator: "./developer/api/common/validator.md"
          - Node:
              - CLI: "./developer/api/node/cli.md"
              - "CLI Utils": "./developer/api/node/cli_utils.md"
              - Config: "./developer/api/node/config.md"
              - DatasetManager: "./developer/api/node/dataset_manager.md"
              - HistoryMonitor: "./developer/api/node/history_monitor.md"
              - Jobs: "./developer/api/node/jobs.md"
              - Node: "./developer/api/node/node.md"
              - NodeStateManager: "./developer/api/node/node_state_manager.md"
              - Requests: "./developer/api/node/requests.md"
              - Round: "./developer/api/node/round.md"
              - Secagg: "./developer/api/node/secagg.md"
              - "Secagg Manager": "./developer/api/node/secagg_manager.md"
              - TrainingPlanSecurityManager: "./developer/api/node/training_plan_security_manager.md"
          - Researcher:
              - Aggregators: "./developer/api/researcher/aggregators.md"
              - CLI: "./developer/api/researcher/cli.md"
              - Config: "./developer/api/researcher/config.md"
              - Datasets: "./developer/api/researcher/datasets.md"
              - Federated Workflows: "./developer/api/researcher/federated_workflows.md"
              - Filetools: "./developer/api/researcher/filetools.md"
              - Jobs: "./developer/api/researcher/jobs.md"
              - Monitor: "./developer/api/researcher/monitor.md"
              - NodeStateAgent: "./developer/api/researcher/node_state_agent.md"
              - Requests: "./developer/api/researcher/requests.md"
              - Secagg: "./developer/api/researcher/secagg.md"
              - Strategies: "./developer/api/researcher/strategies.md"
          - Transport:
              - Client: "./developer/api/transport/client.md"
              - Controller: "./developer/api/transport/controller.md"
              - NodeAgent: "./developer/api/transport/node_agent.md"
              - Server: "./developer/api/transport/server.md"
      - "Usage and Tools": "./developer/usage_and_tools.md"
      - "Continuous Integration": "./developer/ci.md"
      - "Definition of Done": "./developer/definition-of-done.md"
      - "Development Environment": "./developer/development-environment.md"
      - "Testing in Fed-BioMed": "./developer/testing-in-fedbiomed.md"
      - "RPC Protocol and Messages": "./developer/messaging.md"
      - "Federated Analytics": "./developer/federated-analytics.md"
  #    - 'API Reference': ./developer/api/ # Uncomment this if auto generate is active
  - "FAQ & Troubleshooting": "./support/troubleshooting.md"

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  fbm_nav:
    brand_url: https://fedbiomed.org/test-fbm-site/
    brand_logo: assets/img/logo_full.svg
    brand_logo_2x: assets/img/logo_full.svg

    main:
      - title: Docs
        type: link
        url: /

      - title: Getting Started
        type: link
        url: /getting-started/what-is-fedbiomed/

      - title: User Guide
        type: link
        url: /user-guide/glossary/

      - title: Tutorials
        type: dropdown
        items:
          - title: PyTorch
            type: link
            url: /tutorials/pytorch/
          - title: MONAI
            type: link
            url: /tutorials/monai/
          - title: Scikit-Learn
            type: link
            url: /tutorials/scikit-learn/
          - title: Optimizers
            type: link
            url: /tutorials/optimizers/01-fedopt-and-scaffold/
          - title: Analytics
            type: link
            url: /tutorials/analytics/tabular_dataset/
          - title: FLamby
            type: link
            url: /tutorials/flamby/
          - title: Advanced
            type: link
            url: /tutorials/advanced/in-depth-experiment-configuration/
          - title: Security
            type: link
            url: /tutorials/security/differential-privacy-with-opacus-on-fedbiomed/
          - title: Biomedical data
            type: link
            url: /tutorials/medical/medical-image-segmentation-unet-library/
                


  fbm_footer:
    newsletter:
      title: 'Stay <span class="text-fedbiomed-tertiary">updated</span>'
      text: Get the latest Fed-BioMed updates to your inbox
      action: https://sympa.inria.fr/sympa/subscribe/fedbiomed-support
      placeholder: Enter your email

    brand:
      logo: assets/img/logo_icon.png
      name: Fed-BioMed
      copyright: Copyright ©2026

    left_top:
      title: Helpful links
      links:
        - title: Fed-BioMed
          url: https://fedbiomed.org/test-fbm-site/
        - title: Federated Learning
          url: https://fedbiomed.org/test-fbm-site/federated_learning/
        - title: Architecture
          url: https://fedbiomed.org/test-fbm-site/federated_network/#architecture
        - title: Workflow
          url: https://fedbiomed.org/test-fbm-site/federated_network/#workflow
        - title: Security in Practice
          url: https://fedbiomed.org/test-fbm-site/federated_learning/#security-in-practice
        - title: Real world projects
          url: https://fedbiomed.org/test-fbm-site/realworld_projects

    left_bottom:
      title: Documentation
      links:
        - title: Get Started
          url: https://fedbiomed.org/fedbiomed-docs/latest/getting-started/what-is-fedbiomed/
        - title: Installation
          url: https://fedbiomed.org/fedbiomed-docs/latest/getting-started/installation/
        - title: Tutorials
          url: https://fedbiomed.org/fedbiomed-docs/latest/tutorials/pytorch/01_PyTorch_MNIST_Single_Node_Tutorial/
        - title: User Guide
          url: https://fedbiomed.org/fedbiomed-docs/latest/user-guide/glossary/
        - title: Developer
          url: https://fedbiomed.org/fedbiomed-docs/latest/developer/usage_and_tools/
        - title: Examples
          url: https://fedbiomed.org/fedbiomed-docs/latest/getting-started/basic-example/

    right_top:
      title: About
      links:
        - title: Funding & Institutional Support
          url: https://fedbiomed.org/test-fbm-site/about#funding
        - title: Roadmap
          url: https://fedbiomed.org/test-fbm-site/about#roadmap
        - title: FAQ
          url: https://fedbiomed.org/test-fbm-site/faq/
        - title: Support & Contacts
          url: https://fedbiomed.org/test-fbm-site/about#contacts
        - title: How to cite
          url: https://fedbiomed.org/test-fbm-site/about#how-to-cite-us
        - title: Team
          url: https://fedbiomed.org/test-fbm-site/about#team

    social:
      links:
        - title: GitHub
          url: https://github.com/fedbiomed/fedbiomed
          icon: uil uil-github
        - title: LinkedIn
          url: https://www.linkedin.com/groups/12606640/
          icon: uil uil-linkedin
        - title: Email
          url: mailto:fedbiomed@inria.fr
          icon: uil uil-envelope

    right_bottom:
      address: 2004 Rte des Lucioles, 06902 Sophia Antipolis, France
