#!/usr/bin/env bash
#
# wrapper to all vpn container(s) commands
#
#

# detect how the file is run
([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] ||
 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] ||
 [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)) && sourced=1 || sourced=0

[[ "${sourced}" == "1" ]] && echo "This file MUST NOT be sourced" && return

#Activate conda with any of the next commands
#source ~/miniconda3/bin/activate
#source ~/.bashrc

eval "$(conda shell.bash hook)"

CONDA_ENV=$(conda env list | grep fedbiomed-doc-test)
BASE_DIR=$(cd $(dirname $0)/../.. || exit ; pwd)
echo $BASE_DIR

if [ -z "$CONDA_ENV" ]; then
    conda env update -f $BASE_DIR/envs/development/conda/fedbiomed-doc-test.yaml
fi

echo $PWD
conda activate fedbiomed-doc-test
export PYTHONPATH="$BASE_DIR"
cd $BASE_DIR/tests/docstrings/
mkdocs serve --config-file mkdocs.yml