# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fedbiomed.proto import researcher_pb2 as fedbiomed_dot_proto_dot_researcher__pb2


class ResearcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/ResearcherService/Register',
                request_serializer=fedbiomed_dot_proto_dot_researcher__pb2.RegisterRequest.SerializeToString,
                response_deserializer=fedbiomed_dot_proto_dot_researcher__pb2.RegisterResponse.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/ResearcherService/GetTask',
                request_serializer=fedbiomed_dot_proto_dot_researcher__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=fedbiomed_dot_proto_dot_researcher__pb2.GetTaskResponse.FromString,
                )


class ResearcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Register node in researcher component
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResearcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=fedbiomed_dot_proto_dot_researcher__pb2.RegisterRequest.FromString,
                    response_serializer=fedbiomed_dot_proto_dot_researcher__pb2.RegisterResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=fedbiomed_dot_proto_dot_researcher__pb2.GetTaskRequest.FromString,
                    response_serializer=fedbiomed_dot_proto_dot_researcher__pb2.GetTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResearcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResearcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResearcherService/Register',
            fedbiomed_dot_proto_dot_researcher__pb2.RegisterRequest.SerializeToString,
            fedbiomed_dot_proto_dot_researcher__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResearcherService/GetTask',
            fedbiomed_dot_proto_dot_researcher__pb2.GetTaskRequest.SerializeToString,
            fedbiomed_dot_proto_dot_researcher__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
