"""Render the packaged OpenAPI contract as a browsable, offline Markdown reference.

Run from the repository root after editing fedbiomed_node_api/openapi.json.
The JSON download and Markdown page are generated together to avoid separate
hand-maintained API contracts for the website and the installed package.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "fedbiomed_node_api/openapi.json"
DESTINATION = ROOT / "docs/user-guide/nodes"


def render(document):
    lines = [
        "# Node API reference",
        "",
        "<!-- Generated by scripts/generate_api_docs.py; edit the packaged OpenAPI file. -->",
        "",
        "[Download openapi.json](openapi.json) or read the [API quickstart](node-api.md).",
        "",
        document["info"]["description"],
        "",
        "All request and response schemas below use JSON Schema. `$ref` points to",
        "a named schema in the Shared schemas section. `required` lists mandatory",
        "fields; `allOf` means every listed constraint applies. Examples contain",
        "placeholders to replace with your own paths, identifiers and credentials.",
        "",
    ]
    for path, operations in document["paths"].items():
        for method, operation in operations.items():
            lines += [f"## {method.upper()} {path}", "", operation["summary"], ""]
            if operation.get("description"):
                lines += [operation["description"], ""]
            security = operation.get("security", document["security"])
            auth = (
                "None"
                if not security
                else (
                    "Bearer refresh token"
                    if "refreshToken" in security[0]
                    else "Bearer access token"
                )
            )
            lines += [f"Authentication: **{auth}**.", ""]
            if operation.get("parameters"):
                lines += [
                    "Parameters:",
                    "",
                    "```json",
                    json.dumps(operation["parameters"], indent=2),
                    "```",
                    "",
                ]
            if operation.get("requestBody"):
                body = operation["requestBody"]
                lines += [
                    "JSON body "
                    + ("(required):" if body.get("required") else "(optional):"),
                    "",
                ]
                media = body["content"]["application/json"]
                lines += ["```json", json.dumps(media["schema"], indent=2), "```", ""]
                if "example" in media:
                    lines += [
                        "Example:",
                        "",
                        "```json",
                        json.dumps(media["example"], indent=2),
                        "```",
                        "",
                    ]
            else:
                lines += ["No request body.", ""]
            lines += ["Responses:", "", "| Status | Meaning |", "| --- | --- |"]
            response_schemas = {}
            for code, response in operation["responses"].items():
                if "$ref" in response:
                    response = document["components"]["responses"][
                        response["$ref"].rsplit("/", 1)[1]
                    ]
                lines.append(f"| {code} | {response['description']} |")
                for content_type, media in response.get("content", {}).items():
                    response_schemas[f"{code} ({content_type})"] = media["schema"]
            lines.append("")
            for label, schema in response_schemas.items():
                if "$ref" in schema:
                    name = schema["$ref"].rsplit("/", 1)[1]
                    lines += [f"{label}: [{name}](#{name.lower()}).", ""]
                else:
                    lines += [
                        f"{label}:",
                        "",
                        "```json",
                        json.dumps(schema, indent=2),
                        "```",
                        "",
                    ]
    lines += ["## Shared schemas", ""]
    for name, schema in document["components"]["schemas"].items():
        lines += [f"### {name}", "", "```json", json.dumps(schema, indent=2), "```", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if generated docs are outdated"
    )
    args = parser.parse_args()
    source = SOURCE.read_text()
    outputs = {
        DESTINATION / "openapi.json": source,
        DESTINATION / "node-api-reference.md": render(json.loads(source)),
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"Outdated API documentation: {path}\n")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
