#!/usr/bin/env python
#
#
#
#
'''
list the content of an execution queue
'''

import sys
import pprint

import persistqueue


if __name__ == "__main__":

    if len(sys.argv) == 1 :
        print("Need at least one queue directory to to some work")
        sys.exit(-1)

    pp = pprint.PrettyPrinter(indent=2)

    for d in sys.argv[1:]:
        print("==== queue : ", d)
        q = persistqueue.Queue(d)

        if q.qsize() == 0:
            print("(empty)")
        else:
            for i in range(q.qsize()) :
                print("== msg: ", i+1)
                m = q.get_nowait()
                pp.pprint(m)
            print()
