---
name: Fed-BioMed Build test
run-name: Fed-BioMed Build test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - develop

  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:
    inputs:
      full:
        description: "Run full test matrix"
        required: false
        default: "true"


jobs:
  run-tests:
    name: Run Fed-BioMed UNIT-MNIST-DOC Tests
    uses: ./.github/workflows/fbm-generic-test.yml
    secrets: inherit
    with:
      python-versions: ${{ github.event_name == 'schedule' || inputs.full == 'true' && '["3.10","3.11"]' || '["3.11"]' }}
      os-list: ${{ github.event_name == 'schedule' || inputs.full == 'true' && '["ubuntu-latest"]' || '["ubuntu-latest","ubuntu-22.04","macos-latest","macos-m1"]' }}
