---
name: Deploy Fed-BioMed Package
on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  package-compatibility:
    name: Build and test release package
    uses: ./.github/workflows/package-compatibility.yml
    permissions:
      contents: read

  publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: production
    needs: package-compatibility
    permissions:
      id-token: write
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: fedbiomed-package
          path: ./dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Uncomment for testing
        # with:
        #   repository-url: https://test.pypi.org/legacy/

  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    needs: package-compatibility
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract latest changes
        run: ./scripts/changelog

      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: fedbiomed-package

      - name: Make Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: Fed-BioMed Release ${{ github.ref_name }}
          body_path: ./latest_version_changes.txt
