---
name: New End-to-End Test
run-name: fedbiomed-e2e-tests
permissions: write-all
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  e2e-test-auto:
    name: e2e tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22-04,
          - fedora38,
          - macosx-m1
        python-version:
          - 3.10

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout of head
        id: e2e-checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python-version }}"
          command: pip install -U pip  # upgrade pip after installing python

      - name: Run end-to-end tests
        id: e2e-tests-with-pytest
        run: tox -m e2e
        shell: bash -l {0}
