---
name: Endurance Tests
run-name: endurance-tests

on:
  schedule:
    - cron: "0 1 * * 6"  # Run everyweekend at 1 am
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  endurance-test:
    defaults:
    run:
      shell:  bash -l {0}
    name: Endurance Tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22-04
          - fedora38
          - macosx-m1
        python-version:
          - "3.10"
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        id: endurance-checkout
        uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python-version }}"
          command: pip install -U pip  # upgrade pip after installing python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run end-to-end tests
        id: e2e-tests-with-pytest
        run: |
          FEDBIOMED_E2E_DATA_PATH=$HOME/Data/fedbiomed tox -m endurance
        shell: bash -l {0}
