---
name: Test download script
run-name: test-download-script

on:
  push:
    branches:
      - "feature/fix_e2e_tests"

jobs:
  unit-test:
    name: Unit Tests
    defaults:
      run:
        shell: bash -l {0}
    runs-on: 'ubuntu-latest'
    steps:
        - name: Checkout to commit
          uses: actions/checkout@v4

        - name: Setup Fed-BioMed Test Environment
          uses: ./.github/actions/setup-fbm-env
          with:
            python-version: "3.11"
            
        - name: Test
          run: |
            pip install requests
            python tests/end2end/test.py
          shell: bash -l {0}